### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by aamesaa** [blibli-future/athens#3]
- [ ] Unit Testing Service 
- [ ] Mock data in database
- [ ] Testing excel files using junit 

@kabal86 How to do all above?

**Comment by yogiehartanto** [comment]
Unit Testing :
 @InjectMocks --> for service that you want to test (implementation)
example : 
  @InjectMocks
  private EmployeeServiceImpl employeeService;

@Mock --> for create mock up (interface)
example : 
  @Mock
  private EmployeeHistoryService employeeHistoryService;

further example attached

[service and repository(database) unittest.zip](https://github.com/blibli-future/athens/files/946123/service.and.repository.database.unittest.zip)



[excel example unittest.zip](https://github.com/blibli-future/athens/files/946128/excel.example.unittest.zip)
