### ISSUE TITLE
Missing attendance CD

### ISSUE THREAD

**Issue by riencus** [blibli-future/athens#6]
I've just realized that we haven't implemented the CD for the Attendance.
Beside that, I think the R and U for attendance is implemented inside `EmployeeTappingService` with `processGetTapping` and `processUpdateTapping` method.

Question I wanna ask:
- Should it have some method to directly create an Attendance data **not** a tap data?
- Should we separate the tappingService and attendanceService?

Opinion @aamesaa , @sebastianbagya , @kabal86 , anybody?

**Comment by yogiehartanto** [comment]
@arielchristianto what is CD = ?, R = ?, U = ?

**Comment by riencus** [comment]
Sorry for being not clear enough.
CRUD as in Create Read Update Delete

**Comment by yogiehartanto** [comment]
- Should we separate the tappingService and attendanceService?
i think it's related, so you should not separate it

**Comment by sebastianbagya** [comment]
1. I think we can create a C for full attendance data. So attendance can be tapped in and out immediately.

**Comment by riencus** [comment]
> I think we can create a C for full attendance data. So attendance can be tapped in and out immediately.

On where I should implement this @sebastianbagya? `EmployeeTappingService`? Or should I make a new Service just for this?

**Comment by sebastianbagya** [comment]
@arielchristianto, `EmployeeTappingService` because its part of tapping. What do you think @aamesaa ?
